//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfExemPM._01
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMarket
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Author { get; set; }
        public string CountInMarket { get; set; }
        public string CountInStock { get; set; }
        public string Discription { get; set; }
        public string Image { get; set; }
        public string Cost { get; set; }
    }
}
